export { generateContextText } from './contextTemplate.js';
export type { ContextData } from './contextTemplate.js';
export { estimateProgressOverview } from './estimateProgress.js';
export type { Completion, Momentum, StalenessRisk, ProgressOverview } from './estimateProgress.js';
export { inferFocus, inferMilestoneSignals } from './inferFocus.js';
export type { FocusInference, MilestoneSignal } from './inferFocus.js';
export { detectLocale, getTemplates, templates } from './i18n.js';
export type { I18nTemplates } from './i18n.js';
export { recommendNextActions } from './recommendActions.js';
export type { ActionRecommendation } from './recommendActions.js';
